const markdownTable = require('markdown-table');
const dependencyResolver = require('../engine/dependency-resolver');

class ReportGenerator {
    generateAIReadyBundle(sequence, resolver) {
        const report = [];

        report.push('--- AI ARCHITECT PROMPT START ---');
        report.push('You are a Principal Salesforce Solution Architect. I am providing you with a raw metadata-driven migration plan generated by my CLI tool.');
        report.push('**YOUR TASK**:');
        report.push('1. **Refine the Visuals**: Use Mermaid.js to create a high-level dependency flowchart.');
        report.push('2. **Technical Audit**: Identify circular dependencies or "Entity ID not found" risks.');
        report.push('3. **ETL Strategy**: Provide a MuleSoft/Informatica mapping strategy using the External IDs identified.');
        report.push('4. **Execution Table**: Create a detailed tabular view of the loading order, including Object Name, Role (Standard/Custom), and Complexity level.');
        report.push('5. **Executive Summary**: Create a 3-bullet point "Executive Risk Profile" for non-matured teams.');
        report.push('\n**RAW METADATA FOLLOWS**:');

        report.push(`STRATEGIC_SEQUENCE: ${sequence.join(' > ')}`);

        sequence.forEach(obj => {
            const metadata = resolver.objectMetadata[obj];
            const deps = resolver.dependencies[obj] || [];
            report.push(`\n[OBJECT: ${obj}]`);
            report.push(`- Label: ${metadata?.label || obj}`);
            report.push(`- Dependencies: ${deps.join(', ') || 'NONE'}`);
        });

        report.push('\n--- AI ARCHITECT PROMPT END ---');
        return report.join('\n');
    }

    generate(sequence, resolver) {
        const report = [];

        report.push('# 🛫 Salesforce Migration: Executive Flight Plan');
        report.push(`**Prepared by**: Salesforce Migration Architect CLI`);
        report.push(`**Strategic Order**: ${sequence.join(' ➔ ')}`);
        report.push('\n---\n');

        report.push('## 🧩 1. Visual dependency Graph');
        report.push('**How to read this**: Each box is a mission-critical step. The arrows show dependencies. **Objects at the top of the chart must be loaded first.**');

        report.push('\n```mermaid');
        report.push('graph TD');
        sequence.forEach((obj, idx) => {
            const deps = resolver.dependencies[obj] || [];
            const label = `${idx + 1}. ${obj}`;
            if (deps.length === 0) {
                report.push(`    ${obj}["${label}"]:::foundation`);
            } else {
                report.push(`    ${obj}["${label}"]`);
                deps.forEach(p => {
                    if (sequence.includes(p)) {
                        report.push(`    ${p} --> ${obj}`);
                    }
                });
            }
        });
        report.push('    classDef foundation fill:#e1f5fe,stroke:#01579b,stroke-width:2px;');
        report.push('```\n');

        report.push('## 🚦 2. Steps of Execution (The Checklist)');
        report.push('Follow these phases strictly. Do not proceed to the next phase until the current one is 100% verified.');

        const stepsPerPhase = 2;
        for (let i = 0; i < sequence.length; i += stepsPerPhase) {
            const phaseNum = Math.floor(i / stepsPerPhase) + 1;
            const objectsInPhase = sequence.slice(i, i + stepsPerPhase);

            report.push(`### 🏁 Phase ${phaseNum}: ${i === 0 ? 'Foundation Setup' : 'Data Enrichment'}`);
            objectsInPhase.forEach(obj => {
                const checklist = resolver.getChecklist(obj);
                report.push(`\n#### 📦 Step ${sequence.indexOf(obj) + 1}: **${checklist.label}** (${obj})`);
                report.push(`- [ ] **Extract**: Pull from legacy system / CSV source.`);
                report.push(`- [ ] **Map**: Ensure "External ID" is mapped for upserts.`);
                report.push(`- [ ] **Automation Off**: ${checklist.preOps.join(' & ')}.`);
                report.push(`- [ ] **Load**: Upload via Salesforce Bulk API.`);
                report.push(`- [ ] **Verify**: Confirm record counts match source.`);
            });
            report.push('\n');
        }

        report.push('## 👥 3. Team "Who Does What?"');
        report.push('| Role | Primary Responsibility |');
        report.push('| :--- | :--- |');
        report.push('| **Lead Architect** | Approves sequence and data integrity signs-offs. |');
        report.push('| **Migration Crew** | Runs the actual loads; handles CSV errors. |');
        report.push('| **Business Lead** | Validates that fields mapped correctly to business needs. |');

        report.push('\n## ⚠️ 4. Risk Watchlist');
        report.push('1. **Parent Missing**: If Step 1 isn\'t perfectly clean, subsequent steps will fail.');
        report.push('2. **Automation Trap**: Validation Rules or flows must be toggled off or they will hit limits.');

        return report.join('\n');
    }
}

module.exports = new ReportGenerator();
